apiVersion: v2
name: webapp-chart
description: A Helm chart for web application
type: application
version: 0.1.0
appVersion: "1.23"

keywords:
  - web
  - nginx
  - production

maintainers:
  - name: danila
    email: danila@kubsu.edu
