apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-app
  labels:
    app: production
    env: staging
spec:
  replicas: 4
  selector:
    matchLabels:
      app: production
      env: staging
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: production
        env: staging
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
