apiVersion: v1
kind: Pod
metadata:
  name: app-pod
spec:
  containers:
  - name: app-container
    image: busybox
    command: ["sh", "-c", "sleep 3600"]
    env:
    - name: LOG_LEVEL
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: log-level
    volumeMounts:
    - name: db-config-volume
      mountPath: /app/config
  volumes:
  - name: db-config-volume
    configMap:
      name: app-config
      items:
      - key: database.url
        path: db.properties
  restartPolicy: Never
