apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
  labels:
    app: web-demo
data:
  page.title: "Мое приложение"
  welcome.text: "Добро пожаловать в демонстрационное приложение!"
  footer.info: "Версия 1.0 | ConfigMap Demo"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-demo
  labels:
    app: web-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-demo
  template:
    metadata:
      labels:
        app: web-demo
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-content-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-content-volume
        configMap:
          name: web-content
---
apiVersion: v1
kind: Service
metadata:
  name: web-demo-service
  labels:
    app: web-demo
spec:
  type: NodePort
  selector:
    app: web-demo
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30085
