apiVersion: batch/v1
kind: CronJob
metadata:
  name: policy-test-cron
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: long-task
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - sleep 150
          restartPolicy: OnFailure
