apiVersion: batch/v1
kind: CronJob
metadata:
  name: system-info-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: system-info
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - 'echo "Time: $(date), Host: $(hostname), Processes: $(ps aux | wc -l)"'
          restartPolicy: OnFailure
