apiVersion: apps/v1
kind: Deployment
metadata:
  name: probes-diagnostics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probes-diagnostics
  template:
    metadata:
      labels:
        app: probes-diagnostics
    spec:
      containers:
      - name: app
        image: nginx:1.25
        command:
        - sh
        - -c
        - "sleep 10; nginx -g 'daemon off;'"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
