apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness-delay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readiness-delay
  template:
    metadata:
      labels:
        app: readiness-delay
    spec:
      containers:
      - name: app
        image: nginx:1.25
        command:
        - sh
        - -c
        - "sleep 40; nginx -g 'daemon off;'"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
