apiVersion: v1
kind: Pod
metadata:
  name: volume-emptydir
spec:
  containers:
  - name: writer
    image: alpine
    command:
    - sh
    - -c
    - "while true; do date >> /data/log.txt; sleep 5; done"
    volumeMounts:
    - name: shared-data
      mountPath: /data
  - name: reader
    image: alpine
    command:
    - sh
    - -c
    - "tail -f /data/log.txt"
    volumeMounts:
    - name: shared-data
      mountPath: /data
  volumes:
  - name: shared-data
    emptyDir: {}
