apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: multi-service-app
  ports:
  - name: http-backend
    protocol: TCP
    port: 8080
    targetPort: 8080
