apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: ClusterIP
  selector:
    app: multi-service-app
  ports:
  - name: http-frontend
    protocol: TCP
    port: 80
    targetPort: 80
