apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    environment: production
spec:
  type: ClusterIP
  selector:
    app: production-frontend
    environment: production
  ports:
  - name: http-frontend
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
  labels:
    environment: production
spec:
  type: NodePort
  selector:
    app: production-frontend
    environment: production
  ports:
  - name: http-frontend-external
    port: 80
    targetPort: 80
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    environment: production
spec:
  type: ClusterIP
  selector:
    app: production-backend
    environment: production
  ports:
  - name: http-backend
    port: 8080
    targetPort: 8080
