apiVersion: v1
kind: Pod
metadata:
  name: explore-pod
  labels:
    env: prod
    app: main
    tier: frontend
    owner: user
spec:
  containers:
  - name: busy-container
    image: busybox:latest
    ports:
      - containerPort: 8080
    command: ["sh", "-c", "sleep 3600"]

