apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis-app
spec:
  clusterIP: None
  selector:
    app: redis-app
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
