apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-statefulset
spec:
  serviceName: redis-service
  replicas: 3
  selector:
    matchLabels:
      app: redis-app
  template:
    metadata:
      labels:
        app: redis-app
    spec:
      containers:
        - name: app-pod
          image: redis:7-alpine
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
