apiVersion: v1
kind: Pod
metadata:
  name: app-combined-pod
spec:
  containers:
    - name: app-container
      image: nginx:alpine
      env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: database.host
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: database.password
