apiVersion: v1
kind: Secret
metadata:
  name: name-secret
type: Opaque
stringData:
  api-key: my-api-key-value
  auth-token: my-auth-token-value
  encryption-key: |
    -----BEGIN ENCRYPTION KEY-----
    example-encryption-key
    -----END ENCRYPTION KEY-----
