apiVersion: v1
kind: Pod
metadata:
  name: problem-pod-missing-secret
spec:
  containers:
    - name: app-container
      image: nginx:alpine
      env:
        - name: SECRET_VALUE
          valueFrom:
            secretKeyRef:
              name: missing-secret
              key: some-key
