apiVersion: v1
kind: Pod
metadata:
  name: problem-pod-delete-secret
spec:
  containers:
    - name: app-container
      image: nginx:alpine
      volumeMounts:
        - name: secret-volume
          mountPath: /app/secret
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: app-secret
